version: "3"
services:
  chrome:  # selenium用
    image: selenium/standalone-chrome
    restart: always
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
  juman:
    build:
      context: ./docker/juman-knp
      dockerfile: Dockerfile
      args: 
        JUMANPP_VERSION: 1.02
        JUMAN_VERSION: 7.01
        KNP_VERSION: 4.19
    image: juman-knp
    restart: always
    ports:
      - 12000:12000
    tty: true
    command: >
      /bin/bash -c "ruby /tmp/jumanpp-$$JUMANPP_VERSION/script/server.rb --cmd jumanpp -p 12000"
  dev:
    build:
      context: ./docker/japanese-nlp
      dockerfile: Dockerfile
      args: 
        JUMANPP_VERSION: 1.02
        JUMAN_VERSION: 7.01
        KNP_VERSION: 4.19
    image: japanese-nlp
    restart: always
    ports:
      - 8888:8888
      - 5000:5000
    volumes:
      # - .:/volume
      - ../../:/volume
    command: >
      /bin/bash -c "jupyter notebook --no-browser --notebook-dir=/volume &&
      mlflow ui"
  